# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c7decf43-870f-4dd4-ae0f-5459befb5cb0";
      fsType = "ext4";
      options = [
        "noatime" "nodiratime" "discard"
      ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DE96-0FB7";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/16165c81-d375-46f1-99b9-d149ee6b7c8c"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
}
